language: python

install: pip install tox --use-mirrors
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=pep8

before_script:
  - wget https://dl.bintray.com/mitchellh/consul/0.4.1_linux_amd64.zip
  - unzip 0.4.1_linux_amd64.zip
  - start-stop-daemon --start --background --exec `pwd`/consul -- agent -server -data-dir /tmp/consul -bootstrap-expect=1

script:
  - tox -e $TOX_ENV

notifications:
  email:
    - swistakm@gmail.com